### ISSUE TITLE
[UpdateChecker] Update checker shows stale update info in some cases

### ISSUE THREAD

**Issue by zachsaw** [zachsaw/MPDN_Extensions#111] opened 2015-08-04 06:13 UTC
Case 1:
I'm already running v2.39.0 but manually doing a check for updates shows new player available for the same version.

Case 2:
It seems also that the checker does not check again what the current player version is vs what it has cached from the server the last time it ran so the following also erroneously triggers an update prompt.

1. Run old version of MPDN
1. Wait for a while so update checker checks for updates in the background
1. Close MPDN
1. Update MPDN to latest version
1. Run MPDN again - update checker's window pops up with the changelog of an old version (i.e. one version newer than the version of MPDN prior to the manual update)

Note that the correct thing to do would be not to show the update dialog at all since the player is already the latest version.

**Comment by Belphemur** [comment] 2015-08-04 13:23
I'm still trying to reproduce both of the bug. Especially the first one without any success....

Because the way the updater work:
##### On Player Loaded event:
1. Check configuration: Is UpdateChecker enabled/disabled.
1. Version in config (server) newer than version of current player (fetched right now) -> ShowDialog
1. Check for update ASYNC. 

the only reason for which this behaviour could happen is a corruption of the configuration file of the UpdateChecker.

**Comment by zachsaw** [comment] 2015-08-04 13:40
Hmm you're right. I can't reproduce this on this machine. I'll check what's going on with my other machine - might've been a bad config file or something. I don't have access to it at the moment so I'll report back when I do.

**Comment by Belphemur** [comment] 2015-08-14 12:39
I'm closing this. If it happen again can you debug it and give me the value of the different Versions ?

**Closed by Belphemur** 2015-08-14 12:39 UTC
Labels: bug

**Comment by zachsaw** [comment] 2015-08-14 12:41
Yeah, no problem.
